# Generated by Django 2.1.5 on 2019-02-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
